# tox configuration
# Copyright (C) 2003-2026 ITRS Group Ltd. All rights reserved

[tox]

[testenv]
extras = test
basepython = python3
commands =
    python -m coverage run \
        --branch \
        --module pytest {posargs} tests
    python -m coverage report --fail-under=60 --show-missing
commands_post =
    python -m coverage html
